services:
  # Servicio para la base de datos 
  db:
    image: mariadb:latest
    container_name: inventario-db
    restart: always
    environment:
      - MARIADB_DATABASE=inventariodb
      - MARIADB_USER=inventario_user
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inventario-network

  # Servicio de la memoria caché
  redis:
    image: redis:7.2-alpine
    container_name: inventario-cache
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      -  redis_data:/data
    networks:
      - inventario-network

  # Servicio de la aplicación
  app:
    build: ./inventario
    container_name: inventario-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/inventariodb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: inventario_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev
    restart: on-failure
    networks:
      - inventario-network
networks:
  inventario-network:
    driver: bridge 
volumes:
  mariadb_data:
  redis_data: